"""create devices table

Revision ID: 5dcc9bfc0e0f
Revises: 
Create Date: 2026-07-11 13:42:14.195669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcc9bfc0e0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'WARNING', 'FAULT', 'MAINTENANCE', 'UNKNOWN', name='devicestatus'), nullable=False),
    sa.Column('device_type', sa.Enum('PLC', 'RTU', 'SENSOR', 'METER', 'HMI', 'GATEWAY', 'CAMERA', 'OTHER', name='devicetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
